#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ruamel-yaml
Version  : 0.15.80
Release  : 2
URL      : https://files.pythonhosted.org/packages/84/8b/7985d4a9e714e84b2a9cccee99c6d292c94e91b76363677402d794bffffa/ruamel.yaml-0.15.80.tar.gz
Source0  : https://files.pythonhosted.org/packages/84/8b/7985d4a9e714e84b2a9cccee99c6d292c94e91b76363677402d794bffffa/ruamel.yaml-0.15.80.tar.gz
Summary  : ruamel.yaml is a YAML parser/emitter that supports roundtrip preservation of comments, seq/map flow style, and map key order
Group    : Development/Tools
License  : MIT
Requires: ruamel-yaml-license = %{version}-%{release}
Requires: ruamel-yaml-python = %{version}-%{release}
Requires: ruamel-yaml-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : python3-dev

%description
ruamel.yaml
        ===========
        
        ``ruamel.yaml`` is a YAML 1.2 loader/dumper package for Python.

%package license
Summary: license components for the ruamel-yaml package.
Group: Default

%description license
license components for the ruamel-yaml package.


%package python
Summary: python components for the ruamel-yaml package.
Group: Default
Requires: ruamel-yaml-python3 = %{version}-%{release}

%description python
python components for the ruamel-yaml package.


%package python3
Summary: python3 components for the ruamel-yaml package.
Group: Default
Requires: python3-core

%description python3
python3 components for the ruamel-yaml package.


%prep
%setup -q -n ruamel.yaml-0.15.80

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1543734071
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ruamel-yaml
cp LICENSE %{buildroot}/usr/share/package-licenses/ruamel-yaml/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ruamel-yaml/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
